# Generated by Django 5.2.7 on 2025-10-17 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Categoria', models.CharField(max_length=50)),
                ('Descripcion', models.TextField()),
                ('Precio', models.IntegerField()),
                ('Imagen', models.CharField()),
            ],
        ),
    ]
